[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter_program = "8smQAHssVTo3k2k2qMihXwwU5Wmww9WbdSd6PEQ1Abo4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
